import type { Metadata } from "next";
import { gilroy } from "../fonts/gilory";
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gilroy.variable} antialiased`}>
        <Header />
        <div className="app-shell">
          <main className="pt-[110px] pb-16">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
